### ISSUE TITLE
Pre-Trained DenseNet on Chexpert

### ISSUE THREAD

**Issue by nooralahzadeh** [ysmiura/ifcc#2]
Hi, 
Could you please share the pre-trained DenseNet model:  `chexpert_densenet/model_auc14.dict.gz`

Thanks

**Comment by ysmiura** [comment]
I updated the [download.sh](https://github.com/ysmiura/ifcc/blob/master/resources/download.sh) to include the pre-trained CheXpert weights. Please try it out!

**Comment by nooralahzadeh** [comment]
Thanks
