### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by luantunez** [ysmiura/ifcc#4]
Hello and thank you for sharing your work!
I was wondering how can I make an inference with your provided pretrained model checkpoint.
Thank you very much in advance!

**Comment by ysmiura** [comment]
Hi, I am a bit unsure what you exactly want to do, but if you are trying to generate reports from validation/test images, this process is included in `train.py`. If you just want to do an inference from a checkpoint, you can do that by commenting out lines relating to training from `train.py` and specifying the checkpoint with `--baseline-model` option.

**Comment by luantunez** [comment]
Thank you for your response!
And do you have trained models for this that you can share?

**Comment by ysmiura** [comment]
I added an inference script and some pre-trained checkpoints for M2 Transformer. [An example of how to use these script and checkpoints](https://github.com/ysmiura/ifcc#inferring-from-a-checkpoint) is also added to README.

**Comment by luantunez** [comment]
Thank you for your response and for updating the repo! And can I use these tools to make an inference justo on an unseen image? Without using the whole resized dataset and the csv fiiles.
Thank you!

**Comment by ysmiura** [comment]
If your unseen images are from a dataset that is not MIMIC-CXR, a recommend approach is to add a `torch.utils.data.Dataset` class for your dataset. You should also prepare an image preprocess that will make you unseen images similar to MIMIC-CXR images. If you want to infer from an unseen image in MIMIC-CXR (basically a test image) , you can do that by updating [MIMICCXRData class](https://github.com/ysmiura/ifcc/blob/master/clinicgen/data/mimiccxr.py) to only load that unseen image.
