### ISSUE TITLE
about CheXpert&NegBio

### ISSUE THREAD

**Issue by newbietuan** [ysmiura/ifcc#6]
Hello, ysmiura
Thanks for opening your source code. It's very nice works.
when i running the code，i have a few questions, it's mainly about the data preprocessing.
i notice the sections file createed by  create_sections_file.py  are IMPRESSIONS instead FINDINGS, is that right？
and if i should merge  mimic_cxr_number_labeled.csv  to one csv file and zip it to mimic-cxr-2.0.0-chexpert.csv.gz?  and if the negbio(https://github.com/MIT-LCP/mimic-cxr/tree/master/txt/negbio)  in the ifcc code is necessary？

the other question is i have applied the license of mimic_cxr, while i have not seen the mimic-cxr-2.0.0-metadata.csv.gz and mimic-cxr-2.0.0-split.csv.gz, could you please tell me where i can find it?

thank you very much, 
best wishes

**Comment by ysmiura** [comment]
Hi, `mimic_cxr_sectioned.csv.gz` includes both FINDINGS and IMPRESSION. You can extract either section by specifying a corresponding csv column. I am not sure about number-labeled csvs but you can find `mimic-cxr-2.0.0-chexpert.csv.gz`, `mimic-cxr-2.0.0-metadata.csv.gz` and `mimic-cxr-2.0.0-split.csv.gz` in [MIMIC-CXR-JPG](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) (and NOT in MIMIC-CXR).

**Comment by newbietuan** [comment]
> Hi, `mimic_cxr_sectioned.csv.gz` includes both FINDINGS and IMPRESSION. You can extract either section by specifying a corresponding csv column. I am not sure about number-labeled csvs but you can find `mimic-cxr-2.0.0-chexpert.csv.gz`, `mimic-cxr-2.0.0-metadata.csv.gz` and `mimic-cxr-2.0.0-split.csv.gz` in [MIMIC-CXR-JPG](https://physionet.org/content/mimic-cxr-jpg/2.0.0/) (and NOT in MIMIC-CXR).

i see it! thank you very much.
